### ISSUE TITLE
Attempting to test local friskby fails

### ISSUE THREAD

**Issue by pgdr** [FriskByBergen/friskby#107]
Two tests fail:
* test_get (plot.tests.test_url.PlotUrlTest)
* ERROR: test_create (plot.tests.test_model.PlotTest)

```
ERROR: test_get (plot.tests.test_url.PlotUrlTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pgd/friskby/friskby/plot/tests/test_url.py", line 13, in setUp
    self.context = TestContext()
  File "/home/pgd/friskby/friskby/plot/tests/context.py", line 35, in __init__
    post_key = self.key)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: sensor_device.owner_id
```

**Comment by joakim-hove** [comment]
Hmmm - I knew there was one test failing due to plot.ly & pandas incompatibilities, but this seems to go the wrong way :angry:

**Comment by pgdr** [comment]
Unable to reproduce at this time.
